TRAIN:
  ENABLE: True
  DATASET: EgoExo
  BATCH_SIZE: 8
  EVAL_PERIOD: 1
  CHECKPOINT_PERIOD: 1
  AUTO_RESUME: True
  CHECKPOINT_FILE_PATH: /vision/asomaya1/ego_exo/ProficiencyEstimation/TimeSformer/pretrained_ckpts/ego_vlpv2.pth
  FINETUNE: True #If using pretrained_checkpoint for Kinetics, HowTo100M, EgoVLP or EgoVLPv2, set to True
DATA:
  PATH_TO_DATA_DIR: /vision/asomaya1/ego_exo/ProficiencyEstimation/TimeSformer/ego_exo_splits/448pFull
  CAMERA_VIEW: "ego"
  PATH_PREFIX: /vision/asomaya1/ego_exo/data
  NUM_FRAMES: 8
  SAMPLING_RATE: 16
  TRAIN_JITTER_SCALES: [448, 512]
  TRAIN_CROP_SIZE: 448
  TEST_CROP_SIZE: 448
  INPUT_CHANNEL_NUM: [3]
  EGO_EXO_VERSION: 'v1' #options: v1, v2
TENSORBOARD:
  ENABLE: True
  MODEL_VIS:
    ENABLE: True
    GRAD_CAM:
      ENABLE: True
      USE_TRUE_LABEL: True
TIMESFORMER:
  ATTENTION_TYPE: 'divided_space_time'
SOLVER:
  BASE_LR: 0.005
  LR_POLICY: steps_with_relative_lrs
  STEPS: [0, 11, 14]
  LRS: [1, 0.1, 0.01]
  MAX_EPOCH: 20
  MOMENTUM: 0.9
  WEIGHT_DECAY: 1e-4
  OPTIMIZING_METHOD: sgd
MODEL:
  MODEL_NAME: vit_base_patch16_224
  NUM_CLASSES: 4
  ARCH: vit
  LOSS_FUNC: cross_entropy
  DROPOUT_RATE: 0.5
TEST:
  ENABLE: True
  DATASET: EgoExo
  BATCH_SIZE: 32
  NUM_ENSEMBLE_VIEWS: 10
  NUM_SPATIAL_CROPS: 3
DATA_LOADER:
  NUM_WORKERS: 2
  PIN_MEMORY: True
NUM_GPUS: 8
NUM_SHARDS: 1
RNG_SEED: 0
OUTPUT_DIR: ./outputs
